"""add life admin agent models

Revision ID: 1416365db172
Revises: e75f7396c1ca
Create Date: 2026-04-23 16:05:37.338536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1416365db172'
down_revision: Union[str, Sequence[str], None] = 'e75f7396c1ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('life_admin_captures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('normalized_payload', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_life_admin_captures_id'), 'life_admin_captures', ['id'], unique=False)
    op.create_index(op.f('ix_life_admin_captures_user_id'), 'life_admin_captures', ['user_id'], unique=False)
    op.create_table('life_admin_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('is_recurring_template', sa.Boolean(), nullable=False),
    sa.Column('recurrence_parent_id', sa.Integer(), nullable=True),
    sa.Column('escalation_level', sa.Integer(), nullable=False),
    sa.Column('reminder_required', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recurrence_parent_id'], ['life_admin_items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_life_admin_items_id'), 'life_admin_items', ['id'], unique=False)
    op.create_index(op.f('ix_life_admin_items_user_id'), 'life_admin_items', ['user_id'], unique=False)
    op.create_table('life_admin_recurrences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recurrence_rule', sa.String(length=50), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('last_generated_at', sa.DateTime(), nullable=True),
    sa.Column('next_due_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['life_admin_items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_life_admin_recurrences_id'), 'life_admin_recurrences', ['id'], unique=False)
    op.create_index(op.f('ix_life_admin_recurrences_item_id'), 'life_admin_recurrences', ['item_id'], unique=False)
    op.create_index(op.f('ix_life_admin_recurrences_user_id'), 'life_admin_recurrences', ['user_id'], unique=False)
    op.create_table('life_admin_reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reminder_type', sa.String(length=50), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['life_admin_items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_life_admin_reminders_id'), 'life_admin_reminders', ['id'], unique=False)
    op.create_index(op.f('ix_life_admin_reminders_item_id'), 'life_admin_reminders', ['item_id'], unique=False)
    op.create_index(op.f('ix_life_admin_reminders_user_id'), 'life_admin_reminders', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_life_admin_reminders_user_id'), table_name='life_admin_reminders')
    op.drop_index(op.f('ix_life_admin_reminders_item_id'), table_name='life_admin_reminders')
    op.drop_index(op.f('ix_life_admin_reminders_id'), table_name='life_admin_reminders')
    op.drop_table('life_admin_reminders')
    op.drop_index(op.f('ix_life_admin_recurrences_user_id'), table_name='life_admin_recurrences')
    op.drop_index(op.f('ix_life_admin_recurrences_item_id'), table_name='life_admin_recurrences')
    op.drop_index(op.f('ix_life_admin_recurrences_id'), table_name='life_admin_recurrences')
    op.drop_table('life_admin_recurrences')
    op.drop_index(op.f('ix_life_admin_items_user_id'), table_name='life_admin_items')
    op.drop_index(op.f('ix_life_admin_items_id'), table_name='life_admin_items')
    op.drop_table('life_admin_items')
    op.drop_index(op.f('ix_life_admin_captures_user_id'), table_name='life_admin_captures')
    op.drop_index(op.f('ix_life_admin_captures_id'), table_name='life_admin_captures')
    op.drop_table('life_admin_captures')
    # ### end Alembic commands ###
