"""add orchestrator plan storage tables

Revision ID: 404d2bd207f4
Revises: 56ae83c1b3e2
Create Date: 2026-04-22 08:49:58.936487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '404d2bd207f4'
down_revision: Union[str, Sequence[str], None] = '56ae83c1b3e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_briefs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('brief_date', sa.DateTime(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('context_snapshot', sa.Text(), nullable=True),
    sa.Column('planning_notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_briefs_brief_date'), 'plan_briefs', ['brief_date'], unique=False)
    op.create_index(op.f('ix_plan_briefs_id'), 'plan_briefs', ['id'], unique=False)
    op.create_index(op.f('ix_plan_briefs_user_id'), 'plan_briefs', ['user_id'], unique=False)
    op.create_table('plan_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brief_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source_agent', sa.String(length=100), nullable=False),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('recommended_start_at', sa.DateTime(), nullable=True),
    sa.Column('recommended_end_at', sa.DateTime(), nullable=True),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.Column('urgency_score', sa.Float(), nullable=False),
    sa.Column('feasibility_score', sa.Float(), nullable=False),
    sa.Column('final_score', sa.Float(), nullable=False),
    sa.Column('rank_position', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brief_id'], ['plan_briefs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_items_brief_id'), 'plan_items', ['brief_id'], unique=False)
    op.create_index(op.f('ix_plan_items_id'), 'plan_items', ['id'], unique=False)
    op.create_index(op.f('ix_plan_items_user_id'), 'plan_items', ['user_id'], unique=False)
    op.create_table('plan_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_item_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('feedback_type', sa.String(length=50), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_item_id'], ['plan_items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_feedback_id'), 'plan_feedback', ['id'], unique=False)
    op.create_index(op.f('ix_plan_feedback_plan_item_id'), 'plan_feedback', ['plan_item_id'], unique=False)
    op.create_index(op.f('ix_plan_feedback_user_id'), 'plan_feedback', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plan_feedback_user_id'), table_name='plan_feedback')
    op.drop_index(op.f('ix_plan_feedback_plan_item_id'), table_name='plan_feedback')
    op.drop_index(op.f('ix_plan_feedback_id'), table_name='plan_feedback')
    op.drop_table('plan_feedback')
    op.drop_index(op.f('ix_plan_items_user_id'), table_name='plan_items')
    op.drop_index(op.f('ix_plan_items_id'), table_name='plan_items')
    op.drop_index(op.f('ix_plan_items_brief_id'), table_name='plan_items')
    op.drop_table('plan_items')
    op.drop_index(op.f('ix_plan_briefs_user_id'), table_name='plan_briefs')
    op.drop_index(op.f('ix_plan_briefs_id'), table_name='plan_briefs')
    op.drop_index(op.f('ix_plan_briefs_brief_date'), table_name='plan_briefs')
    op.drop_table('plan_briefs')
    # ### end Alembic commands ###
