"""add ai command layer models

Revision ID: 44a1c8338834
Revises: c33c053dcff6
Create Date: 2026-04-24 16:34:31.279989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44a1c8338834'
down_revision: Union[str, Sequence[str], None] = 'c33c053dcff6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_commands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('assistant_message', sa.Text(), nullable=True),
    sa.Column('extracted_payload', sa.Text(), nullable=True),
    sa.Column('created_resources', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_commands_id'), 'ai_commands', ['id'], unique=False)
    op.create_index(op.f('ix_ai_commands_user_id'), 'ai_commands', ['user_id'], unique=False)
    op.create_table('ai_command_revisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('command_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('revision_message', sa.Text(), nullable=False),
    sa.Column('previous_state', sa.Text(), nullable=True),
    sa.Column('revised_state', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['command_id'], ['ai_commands.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_command_revisions_command_id'), 'ai_command_revisions', ['command_id'], unique=False)
    op.create_index(op.f('ix_ai_command_revisions_id'), 'ai_command_revisions', ['id'], unique=False)
    op.create_index(op.f('ix_ai_command_revisions_user_id'), 'ai_command_revisions', ['user_id'], unique=False)
    op.create_table('ai_command_tool_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('command_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tool_name', sa.String(length=150), nullable=False),
    sa.Column('arguments', sa.Text(), nullable=True),
    sa.Column('result_payload', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['command_id'], ['ai_commands.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_command_tool_calls_command_id'), 'ai_command_tool_calls', ['command_id'], unique=False)
    op.create_index(op.f('ix_ai_command_tool_calls_id'), 'ai_command_tool_calls', ['id'], unique=False)
    op.create_index(op.f('ix_ai_command_tool_calls_user_id'), 'ai_command_tool_calls', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_command_tool_calls_user_id'), table_name='ai_command_tool_calls')
    op.drop_index(op.f('ix_ai_command_tool_calls_id'), table_name='ai_command_tool_calls')
    op.drop_index(op.f('ix_ai_command_tool_calls_command_id'), table_name='ai_command_tool_calls')
    op.drop_table('ai_command_tool_calls')
    op.drop_index(op.f('ix_ai_command_revisions_user_id'), table_name='ai_command_revisions')
    op.drop_index(op.f('ix_ai_command_revisions_id'), table_name='ai_command_revisions')
    op.drop_index(op.f('ix_ai_command_revisions_command_id'), table_name='ai_command_revisions')
    op.drop_table('ai_command_revisions')
    op.drop_index(op.f('ix_ai_commands_user_id'), table_name='ai_commands')
    op.drop_index(op.f('ix_ai_commands_id'), table_name='ai_commands')
    op.drop_table('ai_commands')
    # ### end Alembic commands ###
