"""expand phase 1 core models

Revision ID: 56ae83c1b3e2
Revises: 3c531e5b544e
Create Date: 2026-04-20 12:10:43.760546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56ae83c1b3e2'
down_revision: Union[str, Sequence[str], None] = '3c531e5b544e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('notification_type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_history_id'), 'notification_history', ['id'], unique=False)
    op.create_index(op.f('ix_notification_history_user_id'), 'notification_history', ['user_id'], unique=False)
    op.add_column('approvals', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('approvals', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('approvals', sa.Column('resolved_at', sa.DateTime(), nullable=True))
    op.add_column('approvals', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('goals', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('goals', sa.Column('priority', sa.String(length=50), nullable=False))
    op.add_column('goals', sa.Column('target_date', sa.DateTime(), nullable=True))
    op.add_column('goals', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.add_column('goals', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('plans', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('plans', sa.Column('start_at', sa.DateTime(), nullable=True))
    op.add_column('plans', sa.Column('end_at', sa.DateTime(), nullable=True))
    op.add_column('plans', sa.Column('adherence_status', sa.String(length=50), nullable=True))
    op.add_column('plans', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('tasks', sa.Column('scheduled_for', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('estimated_minutes', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('is_recurring', sa.Boolean(), nullable=False))
    op.add_column('tasks', sa.Column('recurrence_rule', sa.String(length=100), nullable=True))
    op.add_column('tasks', sa.Column('parent_task_id', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('reminder_offset_minutes', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_foreign_key(None, 'tasks', 'tasks', ['parent_task_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'updated_at')
    op.drop_column('tasks', 'reminder_offset_minutes')
    op.drop_column('tasks', 'parent_task_id')
    op.drop_column('tasks', 'recurrence_rule')
    op.drop_column('tasks', 'is_recurring')
    op.drop_column('tasks', 'estimated_minutes')
    op.drop_column('tasks', 'completed_at')
    op.drop_column('tasks', 'scheduled_for')
    op.drop_column('plans', 'updated_at')
    op.drop_column('plans', 'adherence_status')
    op.drop_column('plans', 'end_at')
    op.drop_column('plans', 'start_at')
    op.drop_column('plans', 'title')
    op.drop_column('goals', 'updated_at')
    op.drop_column('goals', 'completed_at')
    op.drop_column('goals', 'target_date')
    op.drop_column('goals', 'priority')
    op.drop_column('goals', 'category')
    op.drop_column('approvals', 'updated_at')
    op.drop_column('approvals', 'resolved_at')
    op.drop_column('approvals', 'description')
    op.drop_column('approvals', 'title')
    op.drop_index(op.f('ix_notification_history_user_id'), table_name='notification_history')
    op.drop_index(op.f('ix_notification_history_id'), table_name='notification_history')
    op.drop_table('notification_history')
    # ### end Alembic commands ###
