"""add health routine agent models

Revision ID: 99a72d32cb2f
Revises: be456abb33e5
Create Date: 2026-04-24 13:00:05.526517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99a72d32cb2f'
down_revision: Union[str, Sequence[str], None] = 'be456abb33e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('primary_goal', sa.String(length=100), nullable=False),
    sa.Column('fitness_level', sa.String(length=50), nullable=False),
    sa.Column('preferred_workout_time', sa.String(length=50), nullable=True),
    sa.Column('weekly_workout_target', sa.Integer(), nullable=False),
    sa.Column('minimum_session_minutes', sa.Integer(), nullable=False),
    sa.Column('ideal_session_minutes', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_profiles_id'), 'health_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_health_profiles_user_id'), 'health_profiles', ['user_id'], unique=False)
    op.create_table('health_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recommendation_type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority_score', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_recommendations_id'), 'health_recommendations', ['id'], unique=False)
    op.create_index(op.f('ix_health_recommendations_user_id'), 'health_recommendations', ['user_id'], unique=False)
    op.create_table('recovery_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sleep_hours', sa.Integer(), nullable=True),
    sa.Column('soreness_level', sa.Integer(), nullable=True),
    sa.Column('stress_level', sa.Integer(), nullable=True),
    sa.Column('hydration_level', sa.Integer(), nullable=True),
    sa.Column('energy_level', sa.Integer(), nullable=True),
    sa.Column('recovery_score', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('logged_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_logs_id'), 'recovery_logs', ['id'], unique=False)
    op.create_index(op.f('ix_recovery_logs_user_id'), 'recovery_logs', ['user_id'], unique=False)
    op.create_table('workout_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('workout_type', sa.String(length=100), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('minimum_gap_hours', sa.Integer(), nullable=False),
    sa.Column('recovery_window_hours', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_preferences_id'), 'workout_preferences', ['id'], unique=False)
    op.create_index(op.f('ix_workout_preferences_user_id'), 'workout_preferences', ['user_id'], unique=False)
    op.create_table('workout_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('workout_type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('scheduled_start_at', sa.DateTime(), nullable=True),
    sa.Column('scheduled_end_at', sa.DateTime(), nullable=True),
    sa.Column('planned_minutes', sa.Integer(), nullable=False),
    sa.Column('actual_minutes', sa.Integer(), nullable=True),
    sa.Column('intensity', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('energy_before', sa.Integer(), nullable=True),
    sa.Column('energy_after', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_sessions_id'), 'workout_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_workout_sessions_user_id'), 'workout_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workout_sessions_user_id'), table_name='workout_sessions')
    op.drop_index(op.f('ix_workout_sessions_id'), table_name='workout_sessions')
    op.drop_table('workout_sessions')
    op.drop_index(op.f('ix_workout_preferences_user_id'), table_name='workout_preferences')
    op.drop_index(op.f('ix_workout_preferences_id'), table_name='workout_preferences')
    op.drop_table('workout_preferences')
    op.drop_index(op.f('ix_recovery_logs_user_id'), table_name='recovery_logs')
    op.drop_index(op.f('ix_recovery_logs_id'), table_name='recovery_logs')
    op.drop_table('recovery_logs')
    op.drop_index(op.f('ix_health_recommendations_user_id'), table_name='health_recommendations')
    op.drop_index(op.f('ix_health_recommendations_id'), table_name='health_recommendations')
    op.drop_table('health_recommendations')
    op.drop_index(op.f('ix_health_profiles_user_id'), table_name='health_profiles')
    op.drop_index(op.f('ix_health_profiles_id'), table_name='health_profiles')
    op.drop_table('health_profiles')
    # ### end Alembic commands ###
