"""complete job search schema

Revision ID: be456abb33e5
Revises: 5eb834ca46c4
Create Date: 2026-04-24 12:13:25.872114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be456abb33e5'
down_revision: Union[str, Sequence[str], None] = '5eb834ca46c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_application_followups_application_id'), 'application_followups', ['application_id'], unique=False)
    op.create_index(op.f('ix_application_followups_id'), 'application_followups', ['id'], unique=False)
    op.add_column('companies', sa.Column('website', sa.String(length=255), nullable=True))
    op.alter_column('companies', 'industry',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=True)
    op.drop_index(op.f('ix_companies_user_id'), table_name='companies')
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.drop_column('companies', 'user_id')
    op.drop_column('companies', 'location')
    op.create_index(op.f('ix_interviews_application_id'), 'interviews', ['application_id'], unique=False)
    op.create_index(op.f('ix_interviews_id'), 'interviews', ['id'], unique=False)
    op.create_index(op.f('ix_job_applications_company_id'), 'job_applications', ['company_id'], unique=False)
    op.create_index(op.f('ix_job_applications_id'), 'job_applications', ['id'], unique=False)
    op.create_index(op.f('ix_job_applications_job_posting_id'), 'job_applications', ['job_posting_id'], unique=False)
    op.create_index(op.f('ix_job_applications_resume_variant_id'), 'job_applications', ['resume_variant_id'], unique=False)
    op.create_index(op.f('ix_job_applications_user_id'), 'job_applications', ['user_id'], unique=False)
    op.create_index(op.f('ix_job_postings_company_id'), 'job_postings', ['company_id'], unique=False)
    op.create_index(op.f('ix_job_postings_id'), 'job_postings', ['id'], unique=False)
    op.create_index(op.f('ix_resume_variants_id'), 'resume_variants', ['id'], unique=False)
    op.create_index(op.f('ix_resume_variants_user_id'), 'resume_variants', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resume_variants_user_id'), table_name='resume_variants')
    op.drop_index(op.f('ix_resume_variants_id'), table_name='resume_variants')
    op.drop_index(op.f('ix_job_postings_id'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_company_id'), table_name='job_postings')
    op.drop_index(op.f('ix_job_applications_user_id'), table_name='job_applications')
    op.drop_index(op.f('ix_job_applications_resume_variant_id'), table_name='job_applications')
    op.drop_index(op.f('ix_job_applications_job_posting_id'), table_name='job_applications')
    op.drop_index(op.f('ix_job_applications_id'), table_name='job_applications')
    op.drop_index(op.f('ix_job_applications_company_id'), table_name='job_applications')
    op.drop_index(op.f('ix_interviews_id'), table_name='interviews')
    op.drop_index(op.f('ix_interviews_application_id'), table_name='interviews')
    op.add_column('companies', sa.Column('location', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.create_index(op.f('ix_companies_user_id'), 'companies', ['user_id'], unique=False)
    op.alter_column('companies', 'industry',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_column('companies', 'website')
    op.drop_index(op.f('ix_application_followups_id'), table_name='application_followups')
    op.drop_index(op.f('ix_application_followups_application_id'), table_name='application_followups')
    # ### end Alembic commands ###
