"""add integrations polish observability models

Revision ID: c33c053dcff6
Revises: 99a72d32cb2f
Create Date: 2026-04-24 13:27:04.872547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c33c053dcff6'
down_revision: Union[str, Sequence[str], None] = '99a72d32cb2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_event_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('external_event_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('end_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('raw_payload', sa.Text(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendar_event_snapshots_external_event_id'), 'calendar_event_snapshots', ['external_event_id'], unique=False)
    op.create_index(op.f('ix_calendar_event_snapshots_id'), 'calendar_event_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_calendar_event_snapshots_user_id'), 'calendar_event_snapshots', ['user_id'], unique=False)
    op.create_table('google_integrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('scopes', sa.Text(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_uri', sa.String(length=255), nullable=True),
    sa.Column('expiry', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_google_integrations_id'), 'google_integrations', ['id'], unique=False)
    op.create_index(op.f('ix_google_integrations_user_id'), 'google_integrations', ['user_id'], unique=False)
    op.create_table('integration_sync_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('integration_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('records_processed', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_sync_logs_id'), 'integration_sync_logs', ['id'], unique=False)
    op.create_index(op.f('ix_integration_sync_logs_user_id'), 'integration_sync_logs', ['user_id'], unique=False)
    op.create_table('prompt_run_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('feature_name', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('prompt_preview', sa.Text(), nullable=True),
    sa.Column('response_preview', sa.Text(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_run_logs_id'), 'prompt_run_logs', ['id'], unique=False)
    op.create_index(op.f('ix_prompt_run_logs_user_id'), 'prompt_run_logs', ['user_id'], unique=False)
    op.create_table('gmail_action_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('gmail_message_id', sa.String(length=255), nullable=False),
    sa.Column('sender', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('extracted_title', sa.String(length=255), nullable=False),
    sa.Column('extracted_description', sa.Text(), nullable=True),
    sa.Column('detected_deadline_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('approval_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approval_id'], ['approvals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gmail_action_items_gmail_message_id'), 'gmail_action_items', ['gmail_message_id'], unique=False)
    op.create_index(op.f('ix_gmail_action_items_id'), 'gmail_action_items', ['id'], unique=False)
    op.create_index(op.f('ix_gmail_action_items_user_id'), 'gmail_action_items', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gmail_action_items_user_id'), table_name='gmail_action_items')
    op.drop_index(op.f('ix_gmail_action_items_id'), table_name='gmail_action_items')
    op.drop_index(op.f('ix_gmail_action_items_gmail_message_id'), table_name='gmail_action_items')
    op.drop_table('gmail_action_items')
    op.drop_index(op.f('ix_prompt_run_logs_user_id'), table_name='prompt_run_logs')
    op.drop_index(op.f('ix_prompt_run_logs_id'), table_name='prompt_run_logs')
    op.drop_table('prompt_run_logs')
    op.drop_index(op.f('ix_integration_sync_logs_user_id'), table_name='integration_sync_logs')
    op.drop_index(op.f('ix_integration_sync_logs_id'), table_name='integration_sync_logs')
    op.drop_table('integration_sync_logs')
    op.drop_index(op.f('ix_google_integrations_user_id'), table_name='google_integrations')
    op.drop_index(op.f('ix_google_integrations_id'), table_name='google_integrations')
    op.drop_table('google_integrations')
    op.drop_index(op.f('ix_calendar_event_snapshots_user_id'), table_name='calendar_event_snapshots')
    op.drop_index(op.f('ix_calendar_event_snapshots_id'), table_name='calendar_event_snapshots')
    op.drop_index(op.f('ix_calendar_event_snapshots_external_event_id'), table_name='calendar_event_snapshots')
    op.drop_table('calendar_event_snapshots')
    # ### end Alembic commands ###
