"""add study focus agent models

Revision ID: e75f7396c1ca
Revises: 404d2bd207f4
Create Date: 2026-04-22 11:06:38.830941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e75f7396c1ca'
down_revision: Union[str, Sequence[str], None] = '404d2bd207f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_role', sa.String(length=150), nullable=True),
    sa.Column('target_company', sa.String(length=150), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_tracks_id'), 'interview_tracks', ['id'], unique=False)
    op.create_index(op.f('ix_interview_tracks_user_id'), 'interview_tracks', ['user_id'], unique=False)
    op.create_table('study_streaks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('current_streak_days', sa.Integer(), nullable=False),
    sa.Column('longest_streak_days', sa.Integer(), nullable=False),
    sa.Column('last_completed_session_at', sa.DateTime(), nullable=True),
    sa.Column('last_recovery_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_streaks_id'), 'study_streaks', ['id'], unique=False)
    op.create_index(op.f('ix_study_streaks_user_id'), 'study_streaks', ['user_id'], unique=False)
    op.create_table('study_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('interview_track_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('backlog_size', sa.Integer(), nullable=False),
    sa.Column('priority_weight', sa.Integer(), nullable=False),
    sa.Column('deadline_at', sa.DateTime(), nullable=True),
    sa.Column('estimated_total_minutes', sa.Integer(), nullable=True),
    sa.Column('completed_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['interview_track_id'], ['interview_tracks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_topics_id'), 'study_topics', ['id'], unique=False)
    op.create_index(op.f('ix_study_topics_interview_track_id'), 'study_topics', ['interview_track_id'], unique=False)
    op.create_index(op.f('ix_study_topics_user_id'), 'study_topics', ['user_id'], unique=False)
    op.create_table('study_subtopics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('completed_minutes', sa.Integer(), nullable=False),
    sa.Column('is_high_priority', sa.Boolean(), nullable=False),
    sa.Column('deadline_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['study_topics.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_subtopics_id'), 'study_subtopics', ['id'], unique=False)
    op.create_index(op.f('ix_study_subtopics_topic_id'), 'study_subtopics', ['topic_id'], unique=False)
    op.create_index(op.f('ix_study_subtopics_user_id'), 'study_subtopics', ['user_id'], unique=False)
    op.create_table('study_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('subtopic_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scheduled_start_at', sa.DateTime(), nullable=False),
    sa.Column('scheduled_end_at', sa.DateTime(), nullable=False),
    sa.Column('planned_minutes', sa.Integer(), nullable=False),
    sa.Column('actual_minutes', sa.Integer(), nullable=True),
    sa.Column('energy_preference', sa.String(length=50), nullable=False),
    sa.Column('session_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('carry_forward_count', sa.Integer(), nullable=False),
    sa.Column('explanation_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['subtopic_id'], ['study_subtopics.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['study_topics.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_sessions_id'), 'study_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_study_sessions_subtopic_id'), 'study_sessions', ['subtopic_id'], unique=False)
    op.create_index(op.f('ix_study_sessions_topic_id'), 'study_sessions', ['topic_id'], unique=False)
    op.create_index(op.f('ix_study_sessions_user_id'), 'study_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_study_sessions_user_id'), table_name='study_sessions')
    op.drop_index(op.f('ix_study_sessions_topic_id'), table_name='study_sessions')
    op.drop_index(op.f('ix_study_sessions_subtopic_id'), table_name='study_sessions')
    op.drop_index(op.f('ix_study_sessions_id'), table_name='study_sessions')
    op.drop_table('study_sessions')
    op.drop_index(op.f('ix_study_subtopics_user_id'), table_name='study_subtopics')
    op.drop_index(op.f('ix_study_subtopics_topic_id'), table_name='study_subtopics')
    op.drop_index(op.f('ix_study_subtopics_id'), table_name='study_subtopics')
    op.drop_table('study_subtopics')
    op.drop_index(op.f('ix_study_topics_user_id'), table_name='study_topics')
    op.drop_index(op.f('ix_study_topics_interview_track_id'), table_name='study_topics')
    op.drop_index(op.f('ix_study_topics_id'), table_name='study_topics')
    op.drop_table('study_topics')
    op.drop_index(op.f('ix_study_streaks_user_id'), table_name='study_streaks')
    op.drop_index(op.f('ix_study_streaks_id'), table_name='study_streaks')
    op.drop_table('study_streaks')
    op.drop_index(op.f('ix_interview_tracks_user_id'), table_name='interview_tracks')
    op.drop_index(op.f('ix_interview_tracks_id'), table_name='interview_tracks')
    op.drop_table('interview_tracks')
    # ### end Alembic commands ###
